### ISSUE TITLE
lack of basic axioms and relations

### ISSUE THREAD

**Issue by vtrgdu** [italia/daf-ontologie-vocabolari-controllati#20]
The top level ontology (Level-0) lacks of very basic axioms (inclusion dependencies and disjunctions) and relations (part, dependency, etc). I guess this is a very preliminary version, however I would fix major issues before calling for a broad adoption of this top level.

Here some suggestion:
- Entity disjointWith Event (endurant vs perdurant)
- Activity subClassOf Event
- Abstract vs Concrete partition of Entity (spatio-temporal vs non spatio-temporal)
- Characteristic, Topic, Description subClassOf Abstract
- introduce (at least) notions for SocialObjects and Services
- introduce (at least) part, participation, dependency as ObjectProperties with suitable restrictions

Most of these concepts could be borrowed from DOLCE or other existing top levels. 

Have fun! Daje! :-)

**Comment by anuzzolese** [comment]
Dear Guido,

L0 is still in a preliminary version (v0.2).
Some axioms you are suggesting can be included in next versions for sure.
Nevertheless, the introduction of concepts directly borrowed from DOLCE in L0 should be analysed and mediated by taking into account that L0 is a part of an ontology network, which provides ontologies with conceptualisations of different granularity levels (e.g. ranging from core ontologies about time or units of measure to domain ontologies, such as that for IoT events) .
We are currently keeping L0 as simplest as possible (and here you are right, L0 can be seen as incomplete) because the network is still under construction.

Cheers

**Comment by vtrgdu** [comment]
Dear Andrea,
thank you for clarifying, and please go ahead! Just keep in mind what Einstein used to say, "everything should be made as simple as possible, but not simpler" :-)
Cheers,
Guido

**Comment by aldogangemi** [comment]
Dear Guido, thanks for raising this relevant issue. L0 is just a placeholder for a top level vocabulary to be grown as a generalisation of existing domain ontologies, not to be expected as a full-fledged foundational ontology.
However, we are going to publish a mapping from L0 to DOLCE-Zero (http://www.ontologydesignpatterns.org/ont/d0.owl), a foundational ontology that contains most of what you talk about, either directly, or via its import of DOLCE-Ultralight.
Whether e.g. disjointness axioms must be materialised in L0, or simply obtained via mapping, is something to be checked along experiences in data engineering by the users.

**Comment by vtrgdu** [comment]
Thank you Aldo,
I think that mapping is the best you can do if you go bottom-up as in this case, and DOLCE-Light is a solid conceptual anchorage. Of course one may wonder if bottom-up is the right way to do data integration at the PA level, but I suspect that this is not the place to start this discussion :-)
Cheers,
Guido

**Comment by vtrgdu** [comment]
thank you Giorgia, great job, just a question. Is there any reason for not disjoining e.g. Object and Event? Apparently (bud I did just a quick check) it doesn't break anything, at least as satisfability is concerned. As much as there's no entity without identity (as Quine used to say), there's no ontology without disjointness :-)

**Comment by giorgialodi** [comment]
Guido, just let me check. I will let you know :)

**Comment by giorgialodi** [comment]
Guido, my mistake. I will apply it right now. Thanks for pointing this out!

**Comment by giorgialodi** [comment]
Guido, done :)

**Comment by anuzzolese** [comment]
Dear Guido (@vtrgdu),

I add just a little remark.
Since version 0.2 we added mapping between L0 and Dolce UltraLight+DNS.
Those mappings are published in a separate ontology that imports both L0 and Dolce, and adds alignment axioms between those two ontologies. 
The ontology with the mappings is available in different serialisations (i.e. https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/Ontologie/Livello0/latest/aligns) and can be used if the requirement is to have the expressiveness and the reasoning capabilities of Dolce.
